apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3100
    # memberlist
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946