apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100